quotes = [
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "It always seems impossible until it's done. - Nelson Mandela",
    "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "The best way to predict the future is to create it. - Abraham Lincoln",
    "Believe you can and you're halfway there. - Theodore Roosevelt",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Act as if what you do makes a difference. It does. - William James",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    "If you can dream it, you can do it. - Walt Disney",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The journey of a thousand miles begins with one step. - Lao Tzu",
    "Don’t wait for opportunity. Create it. - Anonymous",
    "Everything you can imagine is real. - Pablo Picasso",
    "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    "Everything has beauty, but not everyone sees it. - Confucius",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "You must be the change you wish to see in the world. - Mahatma Gandhi",
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    "If you’re going through hell, keep going. - Winston Churchill",
    "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "In the end, we only regret the chances we didn’t take. - Lewis Carroll",
    "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "The best way to get started is to quit talking and begin doing. - Walt Disney",
    "You only live once, but if you do it right, once is enough. - Mae West",
    "Good things come to those who wait, but better things come to those who go out and get them. - Anonymous",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Don’t let yesterday take up too much of today. - Will Rogers",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Opportunities don't happen, you create them. - Chris Grosser",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Dream big and dare to fail. - Norman Vaughan",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Everything is hard before it is easy. - Goethe",
    "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. - Jim Rohn",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "The difference between who you are and who you want to be is what you do. - Unknown",
    "There are no shortcuts to any place worth going. - Beverly Sills",
    "You don't have to be perfect to be amazing. - Unknown",
    "Success is not about what you accomplish in your life, it's about what you inspire others to do. - Unknown",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "When we are no longer able to change a situation, we are challenged to change ourselves. - Viktor Frankl",
    "Life is either a daring adventure or nothing at all. - Helen Keller",
    "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    "Life is what happens when you’re busy making other plans. - John Lennon",
    "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
    "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    "A person who never made a mistake never tried anything new. - Albert Einstein",
    "It does not matter how slowly you go, as long as you do not stop. - Confucius",
    "You must do the things you think you cannot do. - Eleanor Roosevelt",
    "The best way to predict your future is to create it. - Abraham Lincoln",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "Nothing is impossible, the word itself says ‘I’m possible!’ - Audrey Hepburn",
    "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
    "The secret of getting ahead is getting started. - Mark Twain",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "The key to success is to focus on goals, not obstacles. - Unknown",
    "Hard work beats talent when talent doesn't work hard. - Tim Notke",
    "The best revenge is massive success. - Frank Sinatra",
    "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    "Success doesn’t just find you. You have to go out and get it. - Unknown",
    "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    "Push yourself, because no one else is going to do it for you. - Unknown",
    "Great things never come from comfort zones. - Unknown",
    "Dream it. Wish it. Do it. - Unknown",
    "Success is what happens after you have survived all of your mistakes. - Anonymous",
    "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    "Do something today that your future self will thank you for. - Unknown",
    "Don’t wait for opportunity. Create it. - Anonymous",
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    "Your limitation—it’s only your imagination. - Unknown",
    "Dream it. Believe it. Build it. - Unknown",
    "You are capable of more than you know. - Glinda, the Good Witch",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently. - Marie Forleo",
    "Great things take time. Be patient. - Unknown",
    "Your future is created by what you do today, not tomorrow. - Robert Kiyosaki",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "Don't stop when you're tired. Stop when you're done. - Unknown",
    "The pain you feel today will be the strength you feel tomorrow. - Unknown",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar"
]
