quotes = {
    1: "The only way to do great work is to love what you do. - Steve Jobs",
    2: "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    3: "Don't watch the clock; do what it does. Keep going. - Sam Levenson",
    4: "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    5: "It always seems impossible until it's done. - Nelson Mandela",
    6: "You miss 100% of the shots you don’t take. - Wayne Gretzky",
    7: "Success is not in what you have, but who you are. - Bo Bennett",
    8: "The best way to predict the future is to create it. - Abraham Lincoln",
    9: "Believe you can and you're halfway there. - Theodore Roosevelt",
    10: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    11: "Act as if what you do makes a difference. It does. - William James",
    12: "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    13: "Do not go where the path may lead, go instead where there is no path and leave a trail. - Ralph Waldo Emerson",
    14: "If you can dream it, you can do it. - Walt Disney",
    15: "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    16: "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    17: "The journey of a thousand miles begins with one step. - Lao Tzu",
    18: "Don’t wait for opportunity. Create it. - Anonymous",
    19: "Everything you can imagine is real. - Pablo Picasso",
    20: "Do what you can, with what you have, where you are. - Theodore Roosevelt",
    21: "Everything has beauty, but not everyone sees it. - Confucius",
    22: "It does not matter how slowly you go as long as you do not stop. - Confucius",
    23: "Life is 10% what happens to us and 90% how we react to it. - Charles R. Swindoll",
    24: "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    25: "You must be the change you wish to see in the world. - Mahatma Gandhi",
    26: "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it. - Jordan Belfort",
    27: "The best revenge is massive success. - Frank Sinatra",
    28: "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    29: "What you get by achieving your goals is not as important as what you become by achieving your goals. - Zig Ziglar",
    30: "If you’re going through hell, keep going. - Winston Churchill",
    31: "Life isn’t about finding yourself. Life is about creating yourself. - George Bernard Shaw",
    32: "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    33: "In the end, we only regret the chances we didn’t take. - Lewis Carroll",
    34: "To live is the rarest thing in the world. Most people exist, that is all. - Oscar Wilde",
    35: "Don’t count the days, make the days count. - Muhammad Ali",
    36: "The best way to get started is to quit talking and begin doing. - Walt Disney",
    37: "You only live once, but if you do it right, once is enough. - Mae West",
    38: "Good things come to those who wait, but better things come to those who go out and get them. - Anonymous",
    39: "The way to get started is to quit talking and begin doing. - Walt Disney",
    40: "Don’t let yesterday take up too much of today. - Will Rogers",
    41: "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    42: "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    43: "Opportunities don't happen, you create them. - Chris Grosser",
    44: "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    45: "You are never too old to set another goal or to dream a new dream. - C.S. Lewis",
    46: "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    47: "Dream big and dare to fail. - Norman Vaughan",
    48: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    49: "Everything is hard before it is easy. - Goethe",
    50: "If you don’t design your own life plan, chances are you’ll fall into someone else’s plan. And guess what they have planned for you? Not much. - Jim Rohn",
    51: "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    52: "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    53: "The difference between who you are and who you want to be is what you do. - Unknown",
    54: "There are no shortcuts to any place worth going. - Beverly Sills",
    55: "You don't have to be perfect to be amazing. - Unknown",
    56: "Success is not about what you accomplish in your life, it's about what you inspire others to do. - Unknown",
    57: "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    58: "When we are no longer able to change a situation, we are challenged to change ourselves. - Viktor Frankl",
    59: "Life is either a daring adventure or nothing at all. - Helen Keller",
    60: "I am not a product of my circumstances. I am a product of my decisions. - Stephen R. Covey",
    61: "Life is what happens when you’re busy making other plans. - John Lennon",
    62: "To succeed in life, you need two things: ignorance and confidence. - Mark Twain",
    63: "You can never cross the ocean until you have the courage to lose sight of the shore. - Christopher Columbus",
    64: "A person who never made a mistake never tried anything new. - Albert Einstein",
    65: "It does not matter how slowly you go, as long as you do not stop. - Confucius",
    66: "You must do the things you think you cannot do. - Eleanor Roosevelt",
    67: "The best way to predict your future is to create it. - Abraham Lincoln",
    68: "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    69: "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    70: "Nothing is impossible, the word itself says ‘I’m possible!’ - Audrey Hepburn",
    71: "There are no limits to what you can accomplish, except the limits you place on your own thinking. - Brian Tracy",
    72: "The secret of getting ahead is getting started. - Mark Twain",
    73: "The way to get started is to quit talking and begin doing. - Walt Disney",
    74: "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    75: "The key to success is to focus on goals, not obstacles. - Unknown",
    76: "Hard work beats talent when talent doesn't work hard. - Tim Notke",
    77: "The best revenge is massive success. - Frank Sinatra",
    78: "Success is the sum of small efforts, repeated day in and day out. - Robert Collier",
    79: "Success doesn’t just find you. You have to go out and get it. - Unknown",
    80: "The only limit to our realization of tomorrow is our doubts of today. - Franklin D. Roosevelt",
    81: "Push yourself, because no one else is going to do it for you. - Unknown",
    82: "Great things never come from comfort zones. - Unknown",
    83: "Dream it. Wish it. Do it. - Unknown",
    84: "Success is what happens after you have survived all of your mistakes. - Anonymous",
    85: "You can't go back and change the beginning, but you can start where you are and change the ending. - C.S. Lewis",
    86: "Do something today that your future self will thank you for. - Unknown",
    87: "Don’t wait for opportunity. Create it. - Anonymous",
    88: "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle. - Christian D. Larson",
    89: "Your limitation—it’s only your imagination. - Unknown",
    90: "Dream it. Believe it. Build it. - Unknown",
    91: "You are capable of more than you know. - Glinda, the Good Witch",
    92: "Success doesn’t come from what you do occasionally, it comes from what you do consistently. - Marie Forleo",
    93: "Great things take time. Be patient. - Unknown",
    94: "Your future is created by what you do today, not tomorrow. - Robert Kiyosaki",
    95: "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    96: "Don't stop when you're tired. Stop when you're done. - Unknown",
    97: "The pain you feel today will be the strength you feel tomorrow. - Unknown",
    98: "If you want to achieve greatness stop asking for permission. - Anonymous",
    99: "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    100: "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar"
}